require "pry-byebug"
require "bundler/setup"
require "json"
require "aws-sdk-ec2"
require "aws-sdk-s3"
require "aws-sdk-route53"

require_relative "./stateless_resources/lister"
require_relative "./stateless_resources/terraform_state_manager"
require_relative "./stateless_resources/aws_resources"
require_relative "./stateless_resources/reporter"
